# Python3 code to demonstrate
# occurrence frequency using
# count()

#initializing string
test_str = "\"The new patients were an 18-year-old female student who returned from Britain on Friday, and a 61-year-old man whose granddaughter and domestic helper was infected previously, according to Dr Chuang Shuk-kwan, head of the Centre for Health Protection’s communicable disease branch.\""
a = test_str.count('a')
b = test_str.count('b')
c = test_str.count('c')
d = test_str.count('d')
e = test_str.count('e')
f = test_str.count('f')
g = test_str.count('g')
h = test_str.count('h')
i = test_str.count('i')
k = test_str.count('k')
l = test_str.count('l')
m = test_str.count('m')
n = test_str.count('n')
o = test_str.count('o')
p = test_str.count('p')
r = test_str.count('r')
s = test_str.count('s')
t = test_str.count('t')
u = test_str.count('u')
v = test_str.count('v')
w = test_str.count('w')
y = test_str.count('y')
B = test_str.count('B')
C = test_str.count('C')
D = test_str.count('D')
F = test_str.count('F')
H = test_str.count('H')
P = test_str.count('P')
S = test_str.count('S')
T = test_str.count('T')
one = test_str.count('1')
six = test_str.count('6')
eight = test_str.count('8')
commas = test_str.count(',')
hyphen = test_str.count('-')
apostrophe = test_str.count('’')
quotationmark = test_str.count('"')
fullstop = test_str.count('.')

#printing result
print (("Count of a is:" + str(a)) +(", ") + ("Count of b is:" + str(b)) +(", ") + ("Count of c is:" + str(c)) + (", ") + ("Count of d is:" + str(d)) + (", ")+ ("Count of e is:" + str(e)) + (", ") + ("Count of f is:" + str(f)) + (", ") + ("Count of g is:" + str(g)) + (", ") + ("Count of h is:" + str(h)) + (", ") + ("Count of i is:" + str(i)) + (", ") + ("Count of k:" + str(k)) + (", ") + ("Count of l is:" + str(l)) + (", ") + ("Count of m is:" + str(m)) + (", ") + ("Count of n is:" + str(n)) + (", ") + ("Count of o is:" + str(o)) + (", ") + ("Counnt of p is:" + str(p)) + (", ") + ("Count of r is:" + str(r)) + (", ") + ("Count of s is:" + str(s)) + (", ") + ("Count of t is:" + str(t)) + (", ") + ("Count of u is:" + str(u)) + (", ") + ("Count of v is:" +str(v)) + (", ") + ("Count of w is:" + str(w)) + (", ") + ("Count of y is:" + str(y)) + (", ") + ("Count of B is:" + str(B)) + (", ") + ("Count of C is:" + str(C)) + ("Count of D is:" + str(D)) + (", ") + ("Count of F is:" + str(F)) + (", ") + ("Count of H is:" + str(H)) + (", ") + ("Count of P is:" + str(P)) + (", ") + ("Count of S is:" + str(S)) + (", ") + ("Count of T is:" + str(T)) + (", ") + ("Count of 1 is:" + str(one)) + (", ") + ("Count of 6 is:" + str(six)) + (", ") + ("Count of 8 is:" + str(eight)) + (", ") + ("Count of comma is:" + str(commas)) + (", ") + ("Count of hypyhen is:" + str(hyphen)) + (", ") + ("Count of apostrophe is:" + str(apostrophe)) + (", ") + ("Count of quotation mark is:" + str(quotationmark)) + (", ") + ("Count of full stop is:" + str(fullstop)))